### ISSUE TITLE
Arabic Support Problem

### ISSUE THREAD

**Issue by devRaafat** [prawnpdf/prawn#921] opened 2015-11-25 07:44 UTC
I'm running my project on Ruby on Rails, and I want to use Prawn to generate pdf reports, for all its advantages. However, I have one main issue: it doesn't support Arabic Language.

I searched for a solution and I found this:

https://rubygems.org/gems/Arabic-Prawn/versions/0.0.1

I installed arabic-prawn 0.0.1 and used this :

Prawn::Document.generate('hello.pdf') do  
  font "#{Prawn::BASEDIR}/data/fonts/artro.ttf"  
  font_size 16
  self.text_direction = :rtl
  long_text = "مرحبا يا العالم"
  text long_text.fix_arabic_glyphs  
end

This is the result: ِarabic words are not appearing

![capture](https://cloud.githubusercontent.com/assets/11060374/11391162/009ec446-9359-11e5-8dca-e0a772d0e3c4.PNG)

I use rails 2.3.5 and prawn 0.6.3.

I couldn't find a solution for this, please help.

**Comment by iamjohnford** [comment] 2015-11-25 09:28
What happens when you don't use that gem? Are the glyphs showing up incorrectly?

**Comment by ACME-Raafat** [comment] 2015-11-25 09:30
I have same result with or without using Arabic prawn.

**Comment by ACME-Raafat** [comment] 2015-11-25 09:30
I have same result with or without using Arabic prawn.

**Comment by iamjohnford** [comment] 2015-11-25 11:21
I don't have artro.ttf but I did a test with [KacstOne.ttf](http://sourceforge.net/projects/arabeyes/files/kacst_fonts/kacst_one_5.0.tar.bz2/download) from http://sourceforge.net/projects/arabeyes/files/kacst_fonts/. It rendered the text but I'm not sure if it is correct. Does that font work if you try it? It could still be related to Prawn but maybe that will help narrow things down.

Also, what version of Ruby and Prawn are you using?

Here's the code I used:

```ruby
Prawn::Document.generate('arabic.pdf') do
  font "KacstOne.ttf"
  font_size 16
  self.text_direction = :rtl
  long_text = "مرحبا يا العالم"
  text long_text
end
```

Here's the output:

<img width="222" alt="screen shot 2015-11-25 at 20 19 23" src="https://cloud.githubusercontent.com/assets/12647/11395997/dc91ab64-93b1-11e5-85ae-5c42c52cbf48.png">

**Comment by ACME-Raafat** [comment] 2015-11-25 12:59
This is great, thank you so much. But how can I display in both languages: Arabic and English? Because when I used KacstOne font, it caused a problem in the English Text. I used this code:

<code> pdf.font_size 18
    long_text = "مرحبا يا العالم"
   pdf.text long_text.fix_arabic_glyphs.connect_arabic_letters  
   long_text = "Hello world"
   pdf.text long_text.fix_arabic_glyphs.connect_arabic_letters

</code>
and this is the output;

![hello_world](https://cloud.githubusercontent.com/assets/11060374/11397806/ea8b62a0-9384-11e5-8686-cb7bb42c30fe.png)

**Comment by iamjohnford** [comment] 2015-11-25 13:25
You may want to change the font depending if you're using Arabic or English. You can change it back and forth as many times as you want. There are good examples of loading fonts in the [manual](http://prawnpdf.org/manual.pdf).

**Comment by ACME-Raafat** [comment] 2015-11-25 13:30
I noticed this, but the problem is that the values I need to display are unknowns, and they could be entered by the user in English or Arabic, that's why I need something that works for both.

**Comment by packetmonkey** [comment] 2015-11-25 13:44
What glyphs can be shown will be controlled by what the font supports. Short term your best solution might be to inspect the string code points and use that information to determine what font to use

```ruby
=> [72, 101, 108, 108, 111, 44, 32, 87, 111, 114, 108, 100, 33]
irb(main):002:0> "مرحبا يا العالم".codepoints
=> [1605, 1585, 1581, 1576, 1575, 32, 1610, 1575, 32, 1575, 1604, 1593, 1575, 1604, 1605]
irb(main):003:0>
```

Also know that you may need to use another library to build up the string and insert it into prawn, we ran into that with Persian support in #871, I apologize if that's not related I don't know much (if anything) about Arabic (or Persian) so the issues related to it may be totally unrelated, but it was another user who was running into problems with rtl text.

**Comment by iamjohnford** [comment] 2015-11-25 13:47
There are some examples out there on how to detect Arabic text: http://stackoverflow.com/questions/7066137/how-to-determine-if-string-contains-arabic-symbols

**Comment by ACME-Raafat** [comment] 2015-11-25 13:49
Thank you for your solution. Before trying it, I found something called fallback fonts:

 http://cookieshq.co.uk/posts/fallback-fonts-in-prawn/

As this links mentions, a fallback font is called when a string contains unsupported characters like Arabic. So I will try it maybe it'll work.

**Comment by pointlessone** [comment] 2024-01-16 15:15
I'm closing this in favour of #1295.

**Closed by pointlessone** 2024-01-16 15:15 UTC
