### ISSUE TITLE
PDF files cannot be embedded via #image

### ISSUE THREAD

**Issue by gioele** [prawnpdf/prawn#1019] opened 2017-04-02 20:19 UTC
Images stored as PDF files cannot be embedded in PDFs using `#image`.

Trying to embed PDF images using `#image` will fail with the following error message.

> /image_handler.rb:38:in `find': image file is an unrecognised format (Prawn::Errors::UnsupportedImageType)

**Comment by pointlessone** [comment] 2017-04-03 08:44
Prawn doesn't support PDF embedding.

PDF is not an image format. You can try externally converting your PDF into one of the supported image formats and including that instead.

---

I will close this issue now as this is expected behaviour and not a bug. If you feel like Prawn should support this please open a new issue with a feature request containing extended description. We will consider it or maybe you or someone else will submit a PR for it.

**Closed by pointlessone** 2017-04-03 08:44 UTC
