### ISSUE TITLE
URL not showing properly

### ISSUE THREAD

**Issue by tsara27** [prawnpdf/prawn#1229] opened 2021-12-08 08:48 UTC
I use Prawn 2.3.0
It's hard to debug why the link is not showing properly. The URL contains strange characters and it's very random, whether the URL is long or short.
I can't find the solution on the documentation or stackoverflow.

Here is the codes:
```ruby
  def answer_link(answer, bounds, document_id, links)
    link           = links[0].to_s
    shortened_link = shorten_link(document_id, link)
    formatted_text_box \
      [{ text: answer || '', link: shortened_link, color: '0000FF' }], size: 9,
      style: :normal, at: [13, bounds.top - 56], width: 130
  end
  ```
  Here is the result:
![Screenshot from 2021-11-30 10-40-50](https://user-images.githubusercontent.com/3486644/145166401-a7660334-b23f-4940-8d62-8efe61ea6f74.png)

```ruby
    https://firebasestorage.googleapis.com/v0/b/vector-development.appspot.com/o/waste_audits%2FMz2UZ1hWaeV91LLh���d�8�CSn�C������&.X�x�s!La���,5�+A�:̕Y�����%�x��;L��c��PѶr5�S5��eJ�?�sC�2��op��ǃ�
    �W������V���S2�c��*�.�׶w;ٮ�S�J��
```  

I thought it's because adding the icon but it's not. When we add the icon with this codes:
```ruby
  bounding_box([72, cursor - 7], width: 20, height: 20) do
    stroke do
      stroke_color COLORS[:action_red_text]
      fill_color COLORS[:action_red_text]
      fill_and_stroke_rounded_rectangle [cursor - 80,cursor], 10, 10, 5
      fill_color 'FFFFFF'
      text_box "!", size: 8, style: :bold, at: [cursor - 76, 18]
    end
  end
```

or with image :

```ruby
image File.join(Rails.root.join('data/images/reports').to_s, '/symbols/excl_mark.png'), at: [12, bounds.top - 7], width: 10
```

the result is still the same:
![Screenshot from 2021-11-30 10-56-28](https://user-images.githubusercontent.com/3486644/145166919-90d59e55-e127-4bf9-8e35-6791a619843d.png)

```ruby
https://firebasestorage.googleapis.com/v0/b/vector-development.appspot.com/o/waste_audits%2FMz2UZ1hWaeV91LLh���d�8�CSn�C������&.X�x�s!La���,5�+A�:̕Y�����%�x��;L��c��PѶr5�S5��eJ�?�sC�2��op��ǃ�
�W������V���S2�c��*�.�׶w;ٮ�S�J��
```

**Comment by gettalong** [comment] 2021-12-08 10:01
Can you provide an example for the values of "link", "shortened_link" and "document_id"? Which font are you using?

**Comment by tsara27** [comment] 2021-12-08 10:05
the document_id is `Mz2UZ1hWaeV91LLhFubG`
shortened_link and link is the same https://firebasestorage.googleapis.com/v0/b/vector-development.appspot.com/o/waste_audits%2FMz2UZ1hWaeV91LLhFubG%2Fsections%2Fwaste_management_policy%2FpolicyDocument%2FMaster%20Document%20Test.pdf?alt=media&token=f5f2ebd6-5434-425f-8135-eef7c5ff3598

**Comment by gettalong** [comment] 2021-12-08 10:18
Thanks - and which font are you using?

**Comment by tsara27** [comment] 2021-12-08 10:22
I use Helvetica

**Comment by gettalong** [comment] 2021-12-08 10:23
@tsara27 Okay, here is a shortened example:

~~~ ruby
require 'prawn'

Prawn::Document.generate("1229.pdf") do |pdf|
  link = 'https://firebasestorage.googleapis.com/v0/b/vector-development.appspot.com/o/waste_audits%2FMz2UZ1hWaeV91LLhFubG%2Fsections%2Fwaste_management_policy%2FpolicyDocument%2FMaster%20Document%20Test.pdf?alt=media&token=f5f2ebd6-5434-425f-8135-eef7c5ff3598'
  pdf.formatted_text_box([{text: link, link: link}])
end
~~~

Which results in this working PDF 
[1229.pdf](https://github.com/prawnpdf/prawn/files/7675262/1229.pdf)

So this seems to work correctly.

**Comment by tsara27** [comment] 2021-12-08 10:30
Thank you - Yes it's working when I only show the link, but it's not when the link is wrapped with another text

**Comment by gettalong** [comment] 2021-12-08 13:46
> Thank you - Yes it's working when I only show the link, but it's not when the link is wrapped with another text

Can you provide some example code for that? Maybe based on my example above?

**Comment by tsara27** [comment] 2021-12-09 01:59
Here is the codes:
```ruby
link = 'https://firebasestorage.googleapis.com/v0/b/vector-development.appspot.com/o/waste_audits%2FMz2UZ1hWaeV91LLhFubG%2Fsections%2Fwaste_management_policy%2FpolicyDocument%2FMaster%20Document%20Test.pdf?alt=media&token=f5f2ebd6-5434-425f-8135-eef7c5ff3598'
formatted_text_box([{ text: "Test", link: link, color: '0000FF' }], at: [13, bounds.top - 56])
```

**Comment by gettalong** [comment] 2021-12-09 06:28
If I replace the code from my example with your code, it still works. Can you provide a full failing example?

**Comment by tsara27** [comment] 2021-12-09 07:04
This is the pdf example
[error_link_1.pdf](https://github.com/prawnpdf/prawn/files/7682914/error_link_1.pdf)

**Comment by gettalong** [comment] 2021-12-09 07:38
I meant a full example of Ruby source code that produces the wrong result.

After inspecting the PDF you linked to I didn't find any hyperlink at all in there. And that file isn't created by Prawn but by Pdfium.

**Comment by tsara27** [comment] 2021-12-09 08:33
[pdf-error-link.pdf](https://github.com/prawnpdf/prawn/files/7683445/pdf-error-link.pdf)

Here is the codes where we load that section

```ruby
def section_field(title, answer, answer_image_urls, links, observation, comment, action, scores, x, height, document_id)
  action_height = action.present? ? get_text_height(action, 9, :normal, 289) : 0
  score_info    = get_color_by_score(scores)

  bounding_box([16, x], width: 490, height: height) do
    section_background_color(bounds, height, scores, score_info)

    if answer_image_urls.present? && answer_image_urls.size.positive?
      bounding_box [13, bounds.top - 46], width: 136, height: (answer_image_urls.size / 2) * 63 do
        answer_image_urls.each_with_index do |image_url, index|
          row    = index / 2
          coords = get_coords(index, bounds, row)

          bounding_box coords, width: 63, height: 63 do
            draw_answer_image(bounds, image_url)
          end
        end
      end
    elsif links.present?
      # this is where we load link
      formatted_text_box \
        [{ text: answer || '', link: links[0], color: '0000FF' }], size: 9,
        style: :normal, at: [13, bounds.top - 56], width: 130
    else
      text_box answer || '', size: 9, style: :normal, at: [13, bounds.top - 56], width: 150
    end
  end
end
```

**Comment by gettalong** [comment] 2021-12-09 09:52
Thanks but that doesn't really help much. I can confirm, however, that the PDF you linked to now contains invalid links. 

Could you please provide a standalone Ruby script that produces such an invalid PDF? I.e. code so that I can run `ruby failing_error.rb` and get an invalid PDF as output?

For future reference: Please treat the time of others as the most precious thing when you ask for help. Anything you can do to save others willing to help you time will most often get you results faster. Like in this case providing - if possible - a small standalone script that produces the invalid PDF file.

**Comment by tsara27** [comment] 2021-12-13 08:29
I found out that the error was caused by encrypt_document method. 
Here is the codes:
```ruby
require 'prawn'

data = [
  {
    title: "Do you have a working knowledge of Health Technical Memorandum (HTM) 07-01?",
    answer: "Familiarise Health Technical Memorandum.pdf",
    observation: "The person conducting the audit does not have a working knowledge of HTM 07-01",
    action: "Familiarise yourself with the Health Technical Memorandum 07-01: Safe management of healthcare waste (HTM 07-01) issued by the Department of Health",
    comment: "When an unknown printer took a galley of type and scrambled it to make a type specimen book",
    link: "https://firebasestorage.googleapis.com/v0/b/vector-development.appspot.com/o/waste_audits%2FMz2UZ1hWaeV91LLhFubG%2Fsections%2Fwaste_management_training%2FtrainingRecordSample%2FMaster%20Document%20Test.pdf?alt=media&token=76bf93cd-1d0a-4735-a7ce-64e7460b9ec7",
    x: 700,
    height: 165,
    action_height: 32,
    score_info: { color: "D6332F", background_color: "F9E0E0", title: "Severe Risk", percent: 100 },
    bounds_top: 163,
    bounds_right: 490
  },
  {
    title: "Does the practice keep training records?",
    answer: "Practice keeps training records.pdf",
    observation: "Signs are used to outline waste segregation",
    action: "Familiarise yourself with the Health Technical Memorandum 07-01: Safe management of healthcare waste (HTM 07-01) issued by the Department of Health",
    comment: "When an unknown printer took a galley of type and scrambled it to make a type specimen book",
    link: "https://firebasestorage.googleapis.com/v0/b/vector-development.appspot.com/o/waste_audits%2FMz2UZ1hWaeV91LLhFubG%2Fsections%2Fhwcn_records%2FhistoricHwcnDocument%2Ft%20is%20a%20long%20established%20fact%20that%20a%20reader%20will%20be%20distracted%20by%20the%20readable%20content%20of%20a%20page%20when%20looking%20at%20its%20layout.%20The%20point%20of%20using%20Lorem%20Ipsum.pdf?alt=media&token=4cd39aa6-9f10-430b-a845-d512bc29aa2b",
    x: 700,
    height: 165,
    action_height: 32,
    score_info: { color: "D6332F", background_color: "F9E0E0", title: "Severe Risk", percent: 100 },
    bounds_top: 163,
    bounds_right: 490
  }
]

Prawn::Document.generate("report_test.pdf") do |pdf|
  pdf.encrypt_document(
    permissions: { modify_contents: false }
  )

  data.each_with_index do |d, index|
    pdf.bounding_box([16, d[:x]], width: d[:bounds_right], height: d[:height]) do
      pdf.stroke do
        pdf.fill_color 'F6F6F6'
        pdf.stroke_color 'F6F6F6'
        pdf.fill_and_stroke_rounded_rectangle [0, d[:height]], d[:bounds_right], d[:height], 4
        pdf.fill_color d[:score_info][:color]
        pdf.stroke_color d[:score_info][:color]
        pdf.fill_and_stroke_rounded_rectangle [d[:bounds_right] - 30, d[:height]], 30, 28, 4
        pdf.fill_and_stroke_rectangle [d[:bounds_right] - 30, d[:height]], 25, 28
        pdf.fill_and_stroke_rectangle [d[:bounds_right] - 30, d[:height] - 5], 30, 23
        pdf.fill_color 'FFFFFF'
        pdf.draw_text "3/3", size: 11, style: :bold, at: [d[:bounds_right] - 22, d[:bounds_top] - 16]
        pdf.fill_color '000000'
        pdf.stroke_color '000000'
      end
  
      pdf.draw_text d[:title], size: 9, style: :bold, at: [13, d[:bounds_top] - 18]
      pdf.fill_color 'AAAAAA'
  
      pdf.draw_text 'Answer', size: 9, style: :bold, at: [13, d[:bounds_top] - 50]
      pdf.draw_text 'Observation', size: 9, style: :bold, at: [171, d[:bounds_top] - 50]
  
      pdf.fill_color '000000'
      pdf.stroke_color '000000'
  
      pdf.formatted_text_box \
        [{ text: d[:answer], link: d[:link], color: '0000FF' }], size: 9,
        style: :normal, at: [13, d[:bounds_top] - 56], width: 130
  
      pdf.text_box d[:observation], size: 9, style: :normal, at: [171, d[:height] - 56], width: 316
  
      pdf.bounding_box [159, d[:bounds_top] - 62 - 20 - 90], width: 313, height: 36 + d[:action_height] do
        pdf.transparent(0.1, 0) do
          pdf.stroke do
            pdf.fill_color 'D6332F'
            pdf.stroke_color 'D6332F'
            pdf.fill_and_stroke_rounded_rectangle [0, d[:bounds_top]], 313, 36 + d[:action_height], 4
          end
        end
  
        pdf.fill_color 'AD2932'
        pdf.text_box 'Action Item', size: 9, style: :bold, at: [27, d[:bounds_top] - 9], width: 150, height: 12
        pdf.fill_color '000000'
        pdf.stroke_color '000000'
  
        pdf.bounding_box [12, d[:bounds_top] - 155], width: 316, height: d[:action_height] do
          pdf.text_box d[:action], size: 9, style: :normal, at: [0, d[:bounds_top]], width: 289, overflow: :expand
        end
      end
    end

    pdf.start_new_page if index.zero?
  end
end

```
And here is the result:
[report_test.pdf](https://github.com/prawnpdf/prawn/files/7702113/report_test.pdf)

But when I remove these codes:

```ruby
pdf.encrypt_document(
  permissions: { modify_contents: false }
)
```

The URL showing correctly

**Comment by gettalong** [comment] 2021-12-13 13:08
@tsara27 Thank you for the example code - I can confirm the problem.

* Generally, I wouldn't rely on Prawns encryption facilities since they use the weakest encryption form possible (RC4 with 40bit). Better encrypt the documents later with a separate tool.

* The encryption implementation of Prawn seems to be incorrect because it doesn't use the trailer's ID field. This *may* be a bug but the specification is not that clear if using an empty trailer ID is valid when using the V=1 R=2 encryption.

* Generally, though, it is possible to decrypt the document (e.g. the values of the info dictionary can be correctly decrypted), so the encryption key calculations seem to be correct.

* **The error is on line https://github.com/prawnpdf/prawn/blob/master/lib/prawn/security.rb#L232 where `\n` is used instead of `\r`. By substituting `\n` with `\r` I got readable output and a correct URL. So you should probably patch your Prawn version until a fix for this is released.**

**Comment by tsara27** [comment] 2021-12-13 13:58
> * Generally, though, it is possible to decrypt the document (e.g. the values of the info dictionary can be correctly decrypted), so the encryption key calculations seem to be correct.
> *

No problem! Thank you for your support too! Really appreciate that.

**Comment by gettalong** [comment] 2022-02-04 17:58
@tsara27 I will close this issue now since I have created a pull request with the needed changes.

**Closed by gettalong** 2022-02-04 17:58 UTC
Labels: confirmed-bug
