### ISSUE TITLE
Problem with text format in symbols

### ISSUE THREAD

**Issue by xamdos** [prawnpdf/prawn#1146] opened 2020-02-13 23:43 UTC
Hi, when I used a character symbol like copyright ©, text formatting has no effect it prawn 2.2
Example: text "©  \u2714", align: :right, size: 12, color: "8FBC47", valign: :center
the color is still in default black
![Screen Shot 2020-02-14 at 7 42 24 AM](https://user-images.githubusercontent.com/61031917/74488591-9fa05a00-4efd-11ea-900b-4405e6dadfd9.png)

**Comment by gettalong** [comment] 2022-02-04 18:18
@xamdos I have tried with this script and Prawn 2.4.0:

~~~ ruby
require 'prawn'

Prawn::Document.generate('test.pdf') do |doc|
  doc.font("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf")
  doc.text "© \u2714", align: :right, size: 12, color: "8FBC47", valign: :center
end
~~~

The output is this:

![image](https://user-images.githubusercontent.com/4104/152581662-956a0519-8e36-4c8a-bcb5-066d51bb2b02.png)

So this works.

Since this issue is already two years old and not reproducible, I will close it now. If you think this is still a problem, please let us know and provide a failing example script.

**Closed by gettalong** 2022-02-04 18:18 UTC
