### ISSUE TITLE
Myanmar font is not being rendered correctly

### ISSUE THREAD

**Issue by pmverma** [prawnpdf/prawn#1125] opened 2019-09-02 08:22 UTC
Hi,

I have following text.
```
require "prawn"

Prawn::Document.generate("hello.pdf") do
  font("PYIDAUNGSU-2.5_REGULAR.TTF") do
    text "ပြည်ထောင်စု သမ္မတ မြန်မာနိုင်ငံတော်‌ - Republic of the Union of Myanmar"
  end
end

```
Following is the rendered pdf which is not correct.

![image](https://user-images.githubusercontent.com/5289123/64099737-071f7e80-cd90-11e9-8459-4a18ef347994.png)

I have attached the font I used.
[PYIDAUNGSU-2.5_REGULAR.TTF.zip](https://github.com/prawnpdf/prawn/files/3565080/PYIDAUNGSU-2.5_REGULAR.TTF.zip)

Let me know what can I help you more.

Regards,
Mohan

**Comment by pmverma** [comment] 2019-09-02 09:23
Note: The result is same with Noto Serif Myanmar fonts.
https://www.google.com/get/noto/#serif-mymr

**Comment by pointlessone** [comment] 2019-09-02 10:50
Could you please confirm, that incorrect rendering can be caused by the lack of ligatures?

**Comment by pmverma** [comment] 2019-09-03 03:58
Thanks @pointlessone for your response.
Sorry for stupid question, but how can I confirm that ligatures is lacking?

Generally in the text editors or word processors, the combination happens automatically.
For eg, from the above example, first letter.

To get `ပြည်`, there sequence goes like `ပ ြ ည ်` and the word processors automatically adjusts them.

1. ပ => ပ
2. ပ + ြ => ပြ
3. ပြ + ည => ပြည
4. ပြည + ် => ပြည်

Regards,
Mohan

**Comment by pmverma** [comment] 2020-04-10 05:39
Hi @pointlessone , I raised an issue to one of the font developer, however, they think that this **might** be a problem with library/platform I am using, the library/platform might not be reordering or resolving viramas, etc.

Please see more at https://github.com/silnrsi/font-padauk/issues/30#issuecomment-611847627

I am having this same problem with all Unicode fonts we have for our language. Some fonts have more rendering issue while some have with less.
I really need this to be fixed.

I just do not know where to start, and how to further this thing.
Can you please help with this?

**Comment by gettalong** [comment] 2020-04-10 06:06
@pmverma In the link you referenced is the mention of font shaping. Prawn doesn't do font shaping since that is quite a complex topic. So if the combination is done through font shaping and not through simple ligatures, you won't get correct results in Prawn, for no font.

However, there is ongoing work to bring OTF support to the library "ttfunk" Prawn is using for fonts. Once this has landed it *might* be easier to implement font shaping in Prawn. But for now this won't work.

**Comment by pointlessone** [comment] 2020-04-10 07:46
Even if it's done with ligatures it won't work either. TTFunk strips all ligature glyphs during subsetting.

**Comment by gettalong** [comment] 2020-04-10 08:27
@pointlessone Really? But how does it do ligatures like 'll' then?

**Comment by pointlessone** [comment] 2020-04-10 08:46
IIRC, TTFunk doesn't touch kerning tables, if you're referring to those. I was speaking of typographic ligatures:
![Typographic ligatures](https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Ligatures.svg/220px-Ligatures.svg.png)

These take a few characters and display them with a single glyph. TTFunk doesn't properly handle that (yet?). It only leaves glyphs for individual characters during subsetting. This results in a less fancy typography in western/Cyrillic scripts but is an issue for scripts that heavily rely on ligatures, like Arabic, or Myanmar.

**Comment by gettalong** [comment] 2020-04-10 21:43
Ah, you are right, I thought about kerning which Prawn supports. The standard 14 PDF fonts partially support ligatures, e.g. Times-Roman supports `f i -> fi`, and I thought that this was implemented. And similarly for TrueType fonts.

**Comment by pointlessone** [comment] 2020-04-11 11:22
Standard fonts are just the ones Adobe promised to always have with their software installed. Since they're pre-installed and not processed by TTFunk they might have all sorts of ligatures and not suffer from subsetting issues.

**Comment by pmverma** [comment] 2020-04-13 13:35
Thanks both @gettalong & @gettalong for your inputs.

Basically I am generating pdf using https://github.com/asciidoctor/asciidoctor-pdf which depends on prawnpdf.

Now I understand I am out of luck here.
Is there any plan to add a support for fonts like Myanmar, in prawn?
Since you are experts here, what will be your suggestions on this?

Regards,
Mohan

**Comment by pointlessone** [comment] 2020-04-13 14:03
There's a consensus that this feature is desired but no concrete plans for the implementation that I'm aware of. I'll be happy to accept a contribution.

**Comment by pmverma** [comment] 2020-04-13 14:18
Thanks @pointlessone .
I think this will be very broad thing to understand and implement.
My current level in this domain is "zero".

However, can you please let me know some resources to understand the issue?

- basic & essentials things to understand
- after that where & how to start

Regards,
Mohan

**Comment by odrotbohm** [comment] 2021-02-08 16:44
Ended up here using Asciidoctor, too, and realizing the lack of ligatures available in the TTF Font ([Vollkorn via Google Fonts](https://fonts.google.com/specimen/Vollkorn?preview.text_type=custom&preview.text=ft%20fi%20ffi%20fft)) not being used. Just as @pmverma, I'd be happy to help but without a few initial pointers it's gonna be hard for me to actually get started.

**Comment by pmverma** [comment] 2021-06-02 11:13
@odrotbohm, Can you please let me know what was your workaround? Or did you stop using this library?

For me, Here is what I have been doing,

-  Build only the `html5` backend then 
- Open it in the browser (Chrome/Edge is better than ) because they render correctly and save as PDF.

However, with this approach, I lose all the `asciidoctor-pdf ` features such as generating TOC with link, page number, etc.
But I believe, I can automate some of those, header & footers using `pdfbox` (not tried yet)

Regards,
Mohan

**Comment by odrotbohm** [comment] 2021-06-08 15:26
There was no workaround for me. Combinations like "fi" are just rendered as two separate letters, not the corresponding ligature.

**Closed** 2023-02-24 16:56 UTC

**Comment by PhilippePerret** [comment] 2023-10-13 09:27
> @odrotbohm, Can you please let me know what was your workaround?

My workaround is to build a new fonte without ligatures… For instance, in this new fonte, let's say "Ligaturae.ttf", I build the "F" glyph with the well-known ligatured "fi". Then, in Prawn:

```ruby
pdf.update do
  text("<font name="Ligaturae">F</font>", 
          **{inline_format: true})
  # write ligatured "fi" in the pdf document
end
```

Of course, with a lot of ligatures, it's a lot of work…

> FYI, l use the very nice [Glyph Mini app](https://glyphsapp.com/buy) to build my fonts.
