### ISSUE TITLE
Persian support missing

### ISSUE THREAD

**Issue by volfgox** [prawnpdf/prawn#871] opened 2015-05-06 08:11 UTC
Words are separated by characters, when generating PDF with Persian fonts like 'B Nazanin'. Is Persian language supported by prawn?

**Comment by packetmonkey** [comment] 2015-05-06 20:30
I suspect the [ttfunk](https://github.com/prawnpdf/ttfunk) library may be having problems with your font. In order to reproduce and begin trying to fix it, we need a script that reproduces the problem and a copy of the ttf font you are trying to use.

I also don't know Persian so some example of what you expected to see would be helpful.

Even after all that it may be hard to track down, but that should at least give us a chance to sort out what is going on.

Other people with similar problems have converted/imported their font using other TTF tools and that appeared to fix the problem for them, it may work for you as well. Otherwise an update to Prawn/TTFunk may be needed.

**Comment by volfgox** [comment] 2015-05-07 14:04
I try to solve the problem by using various fonts. But, the problem still exists there.
Example:

```
require 'prawn'

Prawn::Document.generate("hello.pdf") do
	text_direction :rtl
	font "BNazanin.ttf"
	text "درود دنیا"	# Means 'Hello World'
end
```

You can find 'B Nazanin' font [here](http://awebfont.ir/fonts?cat_id=1&file_id=1069&file_type=ttf).
Generated pdf file by this code looks like:

![1](https://cloud.githubusercontent.com/assets/2599121/7516802/c9f5a3d0-f4e6-11e4-9c44-22a0518b910c.jpg)

and the correct result should look like:

![2](https://cloud.githubusercontent.com/assets/2599121/7516812/d98f18ee-f4e6-11e4-9625-682c2c85b36f.jpg)

Every alphabetic characters in middle east languages like Persian, Kurdish and Arabic, have 5 different shapes.  The name of these shapes are, Common, Isolated, Final, Initial and Medial. One of these shapes are selected in typesetting base on the position of the character in the word, in contrast with the Latin languages which characters have only one shape and no dependency on position in the word.

I develop a gem termed [persian-bechasboon](https://github.com/volfgox/persian-bechasboon) which solve this problem by replacement of disconnected letter with its connected counterparts. The main function of this gem will be applied to the string before calling `text` function of prawn.

I think a function like this should be placed in the core of the prawn to support this type of languages.

**Comment by volfgox** [comment] 2015-05-07 14:06
Pardon me. I reopen this issue.

**Comment by packetmonkey** [comment] 2015-05-08 16:07
What kind of API would you expect for this? I'm not opposed to some kind of text filtering API but looking at the readme for persian-bechasboon, it looks like the problem could be solved with that gem.

```ruby
require 'prawn'
require 'persian-bechasboon'
Prawn::Document.generate("persian.pdf") do
    text_direction :rtl
    font("/path/to/persian/font.ttf") do # For example: B Nazanin
        text "درود دنیا".connect_persian_letters
    end
end
```

Does that fix the problem for you? If in theory every time `Prawn::Document#text` was called with a string that you called `#connect_persian_letters` would the problem be handled?

**Comment by volfgox** [comment] 2015-05-08 18:00
When you type persian in well-known text editor like `textedit` or when you use latex to generate PDF with Persian language, OS or application do character exchanging as what I do in `persian-bechasboon`. 
Yes, this gem fixed my problem. In that, just every character replaced with its appropriate counterpart in a string. So, using this gem can handle the problem.

**Comment by packetmonkey** [comment] 2015-05-20 14:44
What API or functionality would you like to see added to prawn to make using your gem with it more seamless?  I would like to avoid building in support for a lot of special cases but am open to adding APIs that let gem authors extend prawn to handle their use case.

**Comment by volfgox** [comment] 2015-06-07 07:49
In my mind this issue isn't special case. There are millions of people speak languages with right to left direction in writing. Persian, Kurdish and Arabic are three sample of such languages.
Another issue which I faced it is the problem of using English (or other Latin languages) text inside a Persian (or other right to left languages) text. In this problem the characters in English text are typeseted right to left. For example `prawn` appears as `nwarp`.
I think `prawn` should go the way which other typesetting tools like `latex` went before. Existence of A module which manage using of right to left languages like Persian in the heart of `prawn`  seems necessary.

**Comment by packetmonkey** [comment] 2015-07-29 19:09
I can get on board with an api to hook in better text processing for those languages, I completely agree it's a valid use case that can be better handled.

The short term workaround would be to write code such as

```ruby
require 'prawn'

Prawn::Document.generate('output.pdf') do |pdf|
   pdf.text "درود دنیا".connect_persian_letters
end
```

But ideally  you would like to see something like

```ruby
require 'prawn'
require 'prawn-persian-bechasboon'

Prawn::Document.generate('output.pdf') do |pdf|
   pdf.text "درود دنیا"
end
```

Am I understanding correctly?

**Comment by elad** [comment] 2015-08-10 10:39
Hello,

This issue is related to other, more general RTL issues as the RTL visualization in core Prawn is not suitable for actual RTL languages. There are multiple issues on the subject, for example #68, #349, #368, #513, #514, and #700. I took care of part of the issue in the context of Hebrew.

The consensus, as documented in the [right-to-left text section of the manual](https://github.com/prawnpdf/prawn/blob/master/manual/text/right_to_left_text.rb), is that for now this functionality should be installed from 3rd party gems and hopefully, in the future, there will be a `prawn-rtl` gem that will encapsulate all of this functionality (@practicingruby - please correct me if that's not the case anymore).

The work @volfgox has done is a huge step in the right direction in the sense that it takes care of Arabic "cursive" script (Hebrew, like Latin, doesn't have this issue). When we finally have a `prawn-rtl` package it should definitely be part of it. Maybe that's the tilt we need to actually create it. @volfgox are you up for it? :)

**Comment by practicingruby** [comment] 2015-08-10 12:38
@elad: That was the plan... yes. The idea would be that whatever low level and general support functions needed for RTL support should be implemented by Prawn, but then all the specific details could live in an unofficial, semi-official, or official `prawn-rtl` gem (The designation depends on to what extent someone is willing to maintain the gem, and what extent they'll work w. the Prawn core maintainers to coordinate... but is largely unimportant)

**Comment by packetmonkey** [comment] 2015-08-10 15:35
I agree, this now sounds like the best long term plan.

Feel free to open any new issues or PRs with specific changes that need to be made in order for PDF::Core/Prawn to use whatever code ends up being written to support those use cases. 

I'll close this issue for now as there are no directly actionable things in it. I'm exciting to see what language support we can add.

**Closed by packetmonkey** 2015-08-10 15:35 UTC
