### ISSUE TITLE
OTF fonts not properly rendering

### ISSUE THREAD

**Issue by akostadinov** [prawnpdf/prawn#1277] opened 2022-12-14 12:27 UTC
I'm not sure this is related to #1203 or not. But for me no OTF font I've tried worked well. For example  a nice open font like Overpass:
![image](https://user-images.githubusercontent.com/1408661/207594296-1c9fdcd0-8f73-4708-8458-c8b9ddf3df14.png)
While using some TTF font works fine:
![image](https://user-images.githubusercontent.com/1408661/207594521-b00ddda3-c7a4-4cb9-8674-729779316d44.png)

To reproduce, 
* clone https://github.com/akostadinov/prawn-otf-issue
* download and extract Overpass from https://overpassfont.org/
* bundle install
* bundle exec ruby generator.rb

This is basically (copy from Gemfile.lock)
```
    pdf-core (0.9.0)
    prawn (2.4.0)
      pdf-core (~> 0.9.0)
      ttfunk (~> 1.7)
    ttfunk (1.7.0)
```

**Comment by cam-ball** [comment] 2023-06-14 13:48
I'm also having issues with OTF fonts. In my case, I'm loading a Noto font as a `fallback_font`, and the characters missing from my base font simply render as whitespace when trying to use the OTF

[OTF](https://fonts.google.com/noto/specimen/Noto+Sans+SC) (with whitespace highlighted)
<img width="468" alt="Screenshot 2023-06-14 at 9 41 05 AM" src="https://github.com/prawnpdf/prawn/assets/16344962/ba6646b9-a9c1-4994-86d5-e08e146eb6e4">

[TTF](https://github.com/google/fonts/blob/main/ofl/notosanssc/NotoSansSC%5Bwght%5D.ttf)
<img width="469" alt="Screenshot 2023-06-14 at 9 41 33 AM" src="https://github.com/prawnpdf/prawn/assets/16344962/85009ba6-cd75-436e-bae0-4233d2194d55">

```
    pdf-core (0.9.0)
    prawn (2.4.0)
      pdf-core (~> 0.9.0)
      ttfunk (~> 1.7)
    ttfunk (1.7.0)
```

**Comment by leonvogt** [comment] 2024-01-17 11:46
I'm also having issues with OTF fonts. At least on windows machines, on the mac it worked for me.    
My workaround was to convert the OTF fonts to TTF.   
With TTF fonts the problem disappeared.

**Comment by pointlessone** [comment] 2024-01-17 15:30
@leonvogt Do you experience the issue with git versions of TTFunk and Prawn?

**Comment by leonvogt** [comment] 2024-01-17 16:01
@pointlessone I'm not quite sure I understand your question. 
I'm using the released versions on rubygems.org and not the main/master branches, if that's what you mean.     
I'm using the following versions:
```
prawn (2.4.0)
  pdf-core (~> 0.9.0)
  ttfunk (~> 1.7)
```

**Comment by pointlessone** [comment] 2024-01-17 17:18
@leonvogt Yeah, that's what I mean. It was a while since last release and a few bugs have been fixed since. Could you please try master and let me know if your issue has been fixed or not?

**Comment by leonvogt** [comment] 2024-01-17 19:54
I quickly tested with the current version in the master branch, sadly the problem still exists. 
Even worse, with the current version it also incorrectly renders the OTF fonts on the macOS system (14.2.1).

![image](https://github.com/prawnpdf/prawn/assets/17851143/0b815639-3cb5-4005-b63b-7ea36ba219fd)

Used font: Gilroy
Same font with TTF files are no problem and will get rendered fine.

**Comment by pointlessone** [comment] 2024-01-17 19:57
@leonvogt Could you please provide a minimal script that demonstrates the issue, list versions/commit hashes for prawn, pdf-core, and ttfunk gems, and link to the exact font?

**Comment by leonvogt** [comment] 2024-01-18 11:44
@pointlessone sure, I'll try to create a minimal setup in the coming days.

**Comment by leonvogt** [comment] 2024-01-28 15:10
@pointlessone while creating the sample repository I noticed that the most issues are resolved with the current master branch. In my previous comment I mentioned that the issue is still present in the current master branch. Thing is, I only used the current prawn master branch and not the current pdf-core master branch or ttfunk master branch. 
So most things are working now for me. 
One problem I still encountered is that Umlaute are not displayed correctly with .otf fonts. 
Here a sample repository: https://github.com/leonvogt/prawn-otf-font-issue
One thing to mention: I didn't test different fonts. I only tested the mentioned Gilroy font.

**Comment by pointlessone** [comment] 2024-02-14 13:57
@leonvogt I think I've fixed the Umlaute issue. Could you please take another look?

**Comment by pointlessone** [comment] 2024-03-04 10:39
I'll assume that everyone's busy but everything's OK.

Please a new issue if you find things are not in order.

**Closed by pointlessone** 2024-03-04 10:39 UTC

**Comment by leonvogt** [comment] 2024-03-17 17:20
@pointlessone I'm sorry for my late response!
The Umlaute issue seems to be fixed, works just fine with the current version on the master branch. 
Thank you very much!
