### ISSUE TITLE
Stretchy bounding box only respects most recent nested stretchy bounding box's height

### ISSUE THREAD

**Issue by orangethunder** [prawnpdf/prawn#487] opened 2013-05-07 20:10 UTC
I think code says it best.  This is using 1.0.0.rc2.  Apologies if I'm misunderstanding the intended behaviour (or if it's fixed on master):

```
require 'rubygems'
require 'prawn'

Prawn::Document.generate("test.pdf") do
  bounding_box([0, cursor], :width => bounds.right) do
    bounding_box([0, bounds.top], :width => 100) do
      text "Left Line 1"
      text "Left Line 2"
    end
    bounding_box([100, bounds.top], :width => 100) do
      text "Right Line 1"
    end
  end
  text "This line should not overlap, should it?"
end
```

**Comment by richardvenneman** [comment] 2016-05-03 13:28
Does anyone know of a better approach to solving this problem?

**Comment by pointlessone** [comment] 2024-01-16 15:42
So, technically #1177 is a dupe of this but I got to that one earlier so… Anyway, see https://github.com/prawnpdf/prawn/issues/1177#issuecomment-1893777589 for context. We're keeping it the way it is for now.

**Closed by pointlessone** 2024-01-16 15:42 UTC
Labels: change-request
