### ISSUE TITLE
Prawn not working on Rails 5

### ISSUE THREAD

**Issue by victorhazbun87** [prawnpdf/prawn#1000] opened 2016-12-07 07:03 UTC
> require 'prawn'
LoadError: cannot load such file -- prawn

Please tell me what to do to get prawn working on Rails 5.

**Comment by pointlessone** [comment] 2016-12-07 07:20
Hi,

You do the same thing you do with other gems: you put it in your Gemfile.

`Gemfile`:
```ruby
gem 'prawn'
```

---
I will close this issue now as it's not directly related to Prawn but feel free to reopen if you have any additional information or your issue is not resolved.

**Closed by pointlessone** 2016-12-07 07:20 UTC

**Comment by victorhazbun87** [comment] 2016-12-07 07:22
The gem is installed under my Gemfile, you guys will need to provide support on Rails 5 sooner.. Just to let you know...

**Comment by pointlessone** [comment] 2016-12-07 07:43
Prawn is just a library. It doesn't require any special Rails integration. Because of that Prawn sort of supports every Rails version there ever was and will ever be.

There must be a reason why `require` 'prawn'` fails but I'm pretty sure it's not because of Prawn.

If you want us to help you please provide a reduced example that helps reproduce your issue. You may also want to read closer our [Contribution guidelines](https://github.com/prawnpdf/prawn#contributing).
