### ISSUE TITLE
TypeError: can't convert nil into Float

### ISSUE THREAD

**Issue by andreavocado** [prawnpdf/prawn#1344] opened 2024-03-12 11:03 UTC
### Actual Behaviour

With v2.5.0 Following code raises `TypeError: can't convert nil into Float` Exception:

`define_grid(rows: 3, columns: 2)`

### Stacktrace
```
# /baseimage/cache/bundler/ruby/3.2.0/gems/prawn-2.5.0/lib/prawn/grid.rb:152:in `apply_gutter'
# /baseimage/cache/bundler/ruby/3.2.0/gems/prawn-2.5.0/lib/prawn/grid.rb:111:in `initialize'
# /baseimage/cache/bundler/ruby/3.2.0/gems/prawn-2.5.0/lib/prawn/grid.rb:26:in `new'
# /baseimage/cache/bundler/ruby/3.2.0/gems/prawn-2.5.0/lib/prawn/grid.rb:26:in `define_grid'
```

### Introduced
Introduced with commit https://github.com/prawnpdf/prawn/commit/be66ddd0a804a03f6d7979bc773ea0aad0e7ec29#diff-316e1e68603693aee61e42d1332a3b54a403d538da2b4285d0fd0400075cd4fc

### Expected Behaviour
* `define_grid(rows: 3, columns: 2)` uses a default gutter and throws no error
* The documentation is updated

**Comment by gettalong** [comment] 2024-03-12 14:28
Duplicate of #1343 - I'm closing this one.

**Closed by gettalong** 2024-03-12 14:28 UTC
